name: dbtvault_scalefree
version: 0.8.3
require-dbt-version: [">=1.0.0", "<2.0.0"]
config-version: 2

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
docs-paths: ["docs"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

vars:
  dbtvault_scalefree.hash: 'MD5'
  dbtvault_scalefree.beginning_of_all_times: '0001-01-01T00-00-01'
  dbtvault_scalefree.end_of_all_times: '8888-12-31T23-59-59'
  dbtvault_scalefree.timestamp_format: '%Y-%m-%dT%H-%M-%S'
  dbtvault_scalefree.hashkey_input_case_sensitive: FALSE
  dbtvault_scalefree.hashdiff_input_case_sensitive: TRUE
  dbtvault_scalefree.error_value_rsrc: 'ERROR'
  dbtvault_scalefree.unknown_value_rsrc: 'SYSTEM'
