name: "Checking Labels"

permissions:
  issues: write

on: 
  workflow_dispatch:
  pull_request:
    types: [opened]

concurrency:
  group: trigger-group
  cancel-in-progress: false
  
jobs:
  checking-labels:
      runs-on: ubuntu-latest
      steps:
        - name: 
          id: checking-labels
          env: 
            LABEL: ${{ contains(github.event.pull_request.labels.*.name, 'testing') }}
          run: |
            mkdir -p ./label
            echo $LABEL > ./label/label
            echo $LABEL
        - uses: actions/upload-artifact@v4
          with:
            name: label
            path: label/